kind: pipeline
name: default

steps:
- name: test
  image: ubuntu
  commands:
  - sudo apt update
  - sudo apt install -y sdcc build-essential git
  - git clone --depth=1 --recursive https://github.com/OS-Q/T13A.git
  - make -C T13A/serial
