language: python
python:
  - "3.7"

env:
  - PLATFORMIO_PROJECT_DIR=examples/native-blink
  - PLATFORMIO_PROJECT_DIR=examples/stc-blink
  - PLATFORMIO_PROJECT_DIR=examples/stc-header

install:
  - pip install -U https://github.com/OS-Q/S03/archive/master.zip
  - qio platform install file://.

script:
  - qio run -d $PLATFORMIO_PROJECT_DIR

notifications:
  email: false
