name: default

on:
  push:
    branches:
      - master
      - github_actions
    tags:
      - '*'
  pull_request:
    branches:
      - master
      - github_actions

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7]
        project:
          - "esp"
          - "jtag"
          - "serial"

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"

      - name: Install SDCC
        run: sudo apt-get install -y sdcc

      - name: Build
        run: |
          make -C ${{ matrix.project }}
          cp ${{ matrix.project }}/*.hex build/

      - name: Upload
        uses: actions/upload-artifact@v1.0.0
        with:
          name: Firmware_default
          path: build/

