name: SDCC_4.0.0

on:
  push:
    branches:
      - master
      - github_actions
    tags:
      - '*'
  pull_request:
    branches:
      - master
      - github_actions

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7]
        project:
          - "esp"
          - "jtag"
          - "serial"

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install
        run: |
          wget https://sourceforge.net/projects/sdcc/files/sdcc-linux-amd64/4.0.0/sdcc-4.0.0-amd64-unknown-linux2.5.tar.bz2
          tar -xf sdcc-4.0.0-amd64-unknown-linux2.5.tar.bz2
          echo `pwd`/sdcc-4.0.0/bin >> $GITHUB_PATH
          sudo apt install -y build-essential

      - name: Build
        run: |
          make -C ${{ matrix.project }}
          cp ${{ matrix.project }}/*.hex ../build

      - name: Upload
        uses: actions/upload-artifact@v1.0.0
        with:
          name: Firmware
          path: build/
