name: SDCC_4.1.0

on:
  push:
    branches:
      - master
      - github_actions
    tags:
      - '*'
  pull_request:
    branches:
      - master
      - github_actions

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out
      uses: actions/checkout@v2
      with:
        submodules: "recursive"

    - name: Download SDCC
      run: |
        wget https://jaist.dl.sourceforge.net/project/sdcc/sdcc-linux-amd64/4.1.0/sdcc-4.1.0-amd64-unknown-linux2.5.tar.bz2
        tar -xf sdcc-4.1.0-amd64-unknown-linux2.5.tar.bz2
        echo `pwd`/sdcc/bin >> $GITHUB_PATH
        sudo apt install -y build-essential

    - name: Build
      run: make
      working-directory: jtag

    - name: Upload
      uses: actions/upload-artifact@v1.0.0
      with:
        name: Firmware
        path: jtag/
